---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: notification-provider-slack
  namespace: flux-system
spec:
  address: https://slack.com/api/chat.postMessage
  channel: gitopssujoy
  secretRef:
    name: slack-bot-token
  type: slack
  username: sujoy.doc
